version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: smart-rent-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smart-rent-network

volumes:
  postgres_data:

networks:
  smart-rent-network:
    driver: bridge